services:
  app:
    image: 'employee-portal:latest'
    build:
      context: .
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL= jdbc:postgresql://db:5432/employee
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=yes
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres'
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=employee
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yes
