name: 'Terraform GitHub Actions'
on:
  push:
    branch: [wip_terraform]
jobs:
  terraform-apply:
    name: Apply terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: showlist of files
        run: |
         ls -a
      - name: Install ansible
        run: |
          sudo -s
          sudo apt update
          sudo apt upgrade
          sudo apt install ansible
      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./
          auto_approve: true
          variables: |
            aws_region = "${{ secrets.AWS_REGION }}"
            aws_access_key = "${{ secrets.AWS_ACCESS_ID }}"
            aws_secret_key = "${{ secrets.AWS_SECRET_KEY }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: showlist of files
        run: |
         ls -a
    
        

