name: 'Terraform GitHub Actions'
on:
  push:
    branch: [wip_terraform]
jobs:
  terraform-apply:
    name: Apply terraform
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: showlist of files
        run: |
         ls -a
      - name : Install Ansible
        run: |
          sudo apt-get install -y ansible
          ansible --version

      - name: terraform apply
        uses: dflook/terraform-apply@v1
        with:
          path: ./
          auto_approve: true
          variables: |
            aws_region = "${{ secrets.AWS_REGION }}"
            aws_access_key = "${{ secrets.AWS_ACCESS_ID }}"
            aws_secret_key = "${{ secrets.AWS_SECRET_KEY }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: showlist of files
        run: |
         ls -a
      - name : Run Ansible
        run : |
          terraform init -upgrade 
          output=$(terraform output public_ip)
          ansible-playbook -i ouput, Deploy.yml
    
        

