name: 'Terraform GitHub Actions'
on:
  push:
    branch: [wip_terraform]
jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Install Required Packages'
        run: |
          ls -a
          sudo apt-get update -y
          sudo apt-get upgrade -y
          sudo apt-get install -y ansible
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_version: 1.2.1
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: '.'
          tf_actions_comment: true
          args:
            '-backend-config="access_key=${{ secrets.AWS_ACCESS_ID }}" -backend-config="secret_key=${{ secrets.AWS_SECRET_KEY}}"'
        env:
          aws_access_key: ${{ secrets.AWS_SECRET_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Deploy terraform'
        run: terraform apply -auto-approve
        env:
          TF_VAR_aws_access_key: ${{ secrets.aws_access_key }}
          TF_VAR_aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      - name: 'Show list of files'
        run: ls -a
        

